export const empType = {
    GET_DATA: 'GET_EMP',
    GET_DATA_SUCCESS: 'GET_EMP_SUCCESS',
    GET_DETAIL: 'GET_DETAIL',
    GET_DETAIL_SUCCESS: 'GET_DETAIL_SUCCES',
    GET_DETAIL_FAILED: 'GET_DETAIL_FAILED'
}